DROP TABLE IF EXISTS bank_transaction;
DROP TABLE IF EXISTS bank_account;


CREATE TABLE IF NOT EXISTS "bank_transaction"
(
    "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_type"      VARCHAR,
    "service_payment_type"  VARCHAR,
    "transaction_status"    VARCHAR,
    "created_on"            TIMESTAMP,
    "base_transaction_id"   BIGINT,
    "replenishment_sum"     INT,
    "withdraw_sum"          INT,
    "replenishment_bonus"   INT,
    "withdraw_bonus"        INT
);

CREATE TABLE IF NOT EXISTS "bank_account"
(
    "id"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sum"   INT,
    "bonus" INT
);